import { Case } from '@app/classes/model';

export const tiles: Case[][] = [
    [
        { letter: '', bonus: 'TW' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DL' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'TW' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DL' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'TW' },
    ],
    [
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DW' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'TL' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'TL' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DW' },
        { letter: '', bonus: 'xx' },
    ],
    [
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DW' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DL' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DL' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DW' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
    ],
    [
        { letter: '', bonus: 'DL' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DW' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DL' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DW' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DL' },
    ],
    [
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DW' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DW' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
    ],
    [
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'TL' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'TL' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'TL' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'TL' },
        { letter: '', bonus: 'xx' },
    ],
    [
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DL' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DL' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DL' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DL' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
    ],
    [
        { letter: '', bonus: 'TW' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DL' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DW' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DL' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'TW' },
    ],
    [
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DL' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DL' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DL' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DL' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
    ],
    [
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'TL' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'TL' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'TL' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'TL' },
        { letter: '', bonus: 'xx' },
    ],
    [
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DW' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DW' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
    ],
    [
        { letter: '', bonus: 'DL' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DW' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DL' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DW' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DL' },
    ],
    [
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DW' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DL' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DL' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DW' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
    ],
    [
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DW' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'TL' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'TL' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DW' },
        { letter: '', bonus: 'xx' },
    ],
    [
        { letter: '', bonus: 'TW' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DL' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'TW' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'DL' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'xx' },
        { letter: '', bonus: 'TW' },
    ],
];
